arch:
  - amd64
  - ppc64le

language:
  - python

dist:
  - xenial

python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
  - 3.7
before_install:
  - python -m pip install -r requirements.txt

script:
  - python setup.py build
  - python setup.py install

